// <auto-generated />
using System;
using System.Collections.Generic;
using Beridian.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Beridian.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BeridianDbContext))]
    partial class BeridianDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Beridian.Domain.Expenses.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<short>("expense_type")
                        .HasColumnType("smallint")
                        .HasColumnName("expense_type");

                    b.Property<Guid>("financial_period_id")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("ActualAmount", "Beridian.Domain.Expenses.Expense.ActualAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("actual_amount");

                            b1.Property<short>("Currency")
                                .HasColumnType("smallint")
                                .HasColumnName("actual_amount_currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PlannedAmount", "Beridian.Domain.Expenses.Expense.PlannedAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("planned_amount");

                            b1.Property<short>("Currency")
                                .HasColumnType("smallint")
                                .HasColumnName("planned_amount_currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("financial_period_id");

                    b.ToTable("expenses", null, t =>
                        {
                            t.HasCheckConstraint("ck_expenses_actual_amount", "actual_amount >= 0");

                            t.HasCheckConstraint("ck_expenses_currency_consistency", "planned_amount_currency = actual_amount_currency");

                            t.HasCheckConstraint("ck_expenses_currency_values", "planned_amount_currency IN (1)\r\nAND actual_amount_currency IN (1)");

                            t.HasCheckConstraint("ck_expenses_expense_type", "expense_type IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_expenses_installments", "(\r\n    expense_type = 2\r\n    AND current_installment IS NOT NULL\r\n    AND total_installments IS NOT NULL\r\n    AND current_installment > 0\r\n    AND total_installments > 0\r\n    AND current_installment <= total_installments\r\n)\r\nOR\r\n(\r\n    expense_type <> 2\r\n    AND current_installment IS NULL\r\n    AND total_installments IS NULL\r\n)");

                            t.HasCheckConstraint("ck_expenses_name", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_expenses_planned_amount", "planned_amount >= 0");

                            t.HasCheckConstraint("ck_expenses_status", "status IN (1, 2)");
                        });

                    b.HasDiscriminator<short>("expense_type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Beridian.Domain.Expenses.ExpenseDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<Guid>("expense_id")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("ActualAmount", "Beridian.Domain.Expenses.ExpenseDetail.ActualAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("actual_amount");

                            b1.Property<short>("Currency")
                                .HasColumnType("smallint")
                                .HasColumnName("actual_amount_currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("expense_id");

                    b.ToTable("expense_details", null, t =>
                        {
                            t.HasCheckConstraint("ck_expense_details_actual_amount", "actual_amount >= 0");

                            t.HasCheckConstraint("ck_expense_details_currency_consistency", "planned_amount_currency IS NULL\r\nOR planned_amount_currency = actual_amount_currency");

                            t.HasCheckConstraint("ck_expense_details_currency_values", "actual_amount_currency IN (1)\r\nAND\r\n(\r\n    planned_amount_currency IS NULL\r\n    OR planned_amount_currency IN (1)\r\n)");

                            t.HasCheckConstraint("ck_expense_details_description", "btrim(description) <> ''");

                            t.HasCheckConstraint("ck_expense_details_planned_amount", "planned_amount IS NULL OR planned_amount >= 0");

                            t.HasCheckConstraint("ck_expense_details_planned_amount_completeness", "(\r\n    planned_amount IS NULL\r\n    AND planned_amount_currency IS NULL\r\n)\r\nOR\r\n(\r\n    planned_amount IS NOT NULL\r\n    AND planned_amount_currency IS NOT NULL\r\n)");
                        });
                });

            modelBuilder.Entity("Beridian.Domain.FinancialPeriods.FinancialPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.ComplexProperty<Dictionary<string, object>>("OpeningBalance", "Beridian.Domain.FinancialPeriods.FinancialPeriod.OpeningBalance#TransferredBalance", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty<Dictionary<string, object>>("Amount", "Beridian.Domain.FinancialPeriods.FinancialPeriod.OpeningBalance#TransferredBalance.Amount#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("opening_balance_amount");

                                    b2.Property<short>("Currency")
                                        .HasColumnType("smallint")
                                        .HasColumnName("opening_balance_currency");
                                });
                        });

                    b.HasKey("Id");

                    b.ToTable("financial_periods", null, t =>
                        {
                            t.HasCheckConstraint("ck_financial_periods_month", "period_month BETWEEN 1 AND 12");

                            t.HasCheckConstraint("ck_financial_periods_opening_balance_currency", "opening_balance_currency IN (1)");

                            t.HasCheckConstraint("ck_financial_periods_status", "status IN (1, 2)");

                            t.HasCheckConstraint("ck_financial_periods_year", "period_year BETWEEN 1 AND 9999");
                        });
                });

            modelBuilder.Entity("Beridian.Domain.Incomes.Income", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("financial_period_id")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("ActualAmount", "Beridian.Domain.Incomes.Income.ActualAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("actual_amount");

                            b1.Property<short>("Currency")
                                .HasColumnType("smallint")
                                .HasColumnName("actual_amount_currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PlannedAmount", "Beridian.Domain.Incomes.Income.PlannedAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("planned_amount");

                            b1.Property<short>("Currency")
                                .HasColumnType("smallint")
                                .HasColumnName("planned_amount_currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("financial_period_id");

                    b.ToTable("incomes", null, t =>
                        {
                            t.HasCheckConstraint("ck_incomes_actual_amount", "actual_amount >= 0");

                            t.HasCheckConstraint("ck_incomes_currency_consistency", "planned_amount_currency = actual_amount_currency");

                            t.HasCheckConstraint("ck_incomes_currency_values", "planned_amount_currency IN (1)\r\nAND actual_amount_currency IN (1)");

                            t.HasCheckConstraint("ck_incomes_name", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_incomes_planned_amount", "planned_amount >= 0");

                            t.HasCheckConstraint("ck_incomes_status", "status IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Beridian.Domain.Investments.Investment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("financial_period_id")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("ActualAmount", "Beridian.Domain.Investments.Investment.ActualAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("actual_amount");

                            b1.Property<short>("Currency")
                                .HasColumnType("smallint")
                                .HasColumnName("actual_amount_currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PlannedAmount", "Beridian.Domain.Investments.Investment.PlannedAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("planned_amount");

                            b1.Property<short>("Currency")
                                .HasColumnType("smallint")
                                .HasColumnName("planned_amount_currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("financial_period_id");

                    b.ToTable("investments", null, t =>
                        {
                            t.HasCheckConstraint("ck_investments_actual_amount", "actual_amount >= 0");

                            t.HasCheckConstraint("ck_investments_currency_consistency", "planned_amount_currency = actual_amount_currency");

                            t.HasCheckConstraint("ck_investments_currency_values", "planned_amount_currency IN (1)\r\nAND actual_amount_currency IN (1)");

                            t.HasCheckConstraint("ck_investments_name", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_investments_planned_amount", "planned_amount >= 0");

                            t.HasCheckConstraint("ck_investments_status", "status IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Beridian.Domain.Expenses.DiscretionaryExpense", b =>
                {
                    b.HasBaseType("Beridian.Domain.Expenses.Expense");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_expenses_actual_amount", "actual_amount >= 0");

                            t.HasCheckConstraint("ck_expenses_currency_consistency", "planned_amount_currency = actual_amount_currency");

                            t.HasCheckConstraint("ck_expenses_currency_values", "planned_amount_currency IN (1)\r\nAND actual_amount_currency IN (1)");

                            t.HasCheckConstraint("ck_expenses_expense_type", "expense_type IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_expenses_installments", "(\r\n    expense_type = 2\r\n    AND current_installment IS NOT NULL\r\n    AND total_installments IS NOT NULL\r\n    AND current_installment > 0\r\n    AND total_installments > 0\r\n    AND current_installment <= total_installments\r\n)\r\nOR\r\n(\r\n    expense_type <> 2\r\n    AND current_installment IS NULL\r\n    AND total_installments IS NULL\r\n)");

                            t.HasCheckConstraint("ck_expenses_name", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_expenses_planned_amount", "planned_amount >= 0");

                            t.HasCheckConstraint("ck_expenses_status", "status IN (1, 2)");
                        });

                    b.HasDiscriminator().HasValue((short)3);
                });

            modelBuilder.Entity("Beridian.Domain.Expenses.FixedTermExpense", b =>
                {
                    b.HasBaseType("Beridian.Domain.Expenses.Expense");

                    b.Property<int>("CurrentInstallment")
                        .HasColumnType("integer")
                        .HasColumnName("current_installment");

                    b.Property<int>("TotalInstallments")
                        .HasColumnType("integer")
                        .HasColumnName("total_installments");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_expenses_actual_amount", "actual_amount >= 0");

                            t.HasCheckConstraint("ck_expenses_currency_consistency", "planned_amount_currency = actual_amount_currency");

                            t.HasCheckConstraint("ck_expenses_currency_values", "planned_amount_currency IN (1)\r\nAND actual_amount_currency IN (1)");

                            t.HasCheckConstraint("ck_expenses_expense_type", "expense_type IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_expenses_installments", "(\r\n    expense_type = 2\r\n    AND current_installment IS NOT NULL\r\n    AND total_installments IS NOT NULL\r\n    AND current_installment > 0\r\n    AND total_installments > 0\r\n    AND current_installment <= total_installments\r\n)\r\nOR\r\n(\r\n    expense_type <> 2\r\n    AND current_installment IS NULL\r\n    AND total_installments IS NULL\r\n)");

                            t.HasCheckConstraint("ck_expenses_name", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_expenses_planned_amount", "planned_amount >= 0");

                            t.HasCheckConstraint("ck_expenses_status", "status IN (1, 2)");
                        });

                    b.HasDiscriminator().HasValue((short)2);
                });

            modelBuilder.Entity("Beridian.Domain.Expenses.RecurringExpense", b =>
                {
                    b.HasBaseType("Beridian.Domain.Expenses.Expense");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_expenses_actual_amount", "actual_amount >= 0");

                            t.HasCheckConstraint("ck_expenses_currency_consistency", "planned_amount_currency = actual_amount_currency");

                            t.HasCheckConstraint("ck_expenses_currency_values", "planned_amount_currency IN (1)\r\nAND actual_amount_currency IN (1)");

                            t.HasCheckConstraint("ck_expenses_expense_type", "expense_type IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_expenses_installments", "(\r\n    expense_type = 2\r\n    AND current_installment IS NOT NULL\r\n    AND total_installments IS NOT NULL\r\n    AND current_installment > 0\r\n    AND total_installments > 0\r\n    AND current_installment <= total_installments\r\n)\r\nOR\r\n(\r\n    expense_type <> 2\r\n    AND current_installment IS NULL\r\n    AND total_installments IS NULL\r\n)");

                            t.HasCheckConstraint("ck_expenses_name", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_expenses_planned_amount", "planned_amount >= 0");

                            t.HasCheckConstraint("ck_expenses_status", "status IN (1, 2)");
                        });

                    b.HasDiscriminator().HasValue((short)1);
                });

            modelBuilder.Entity("Beridian.Domain.Expenses.Expense", b =>
                {
                    b.HasOne("Beridian.Domain.FinancialPeriods.FinancialPeriod", null)
                        .WithMany("Expenses")
                        .HasForeignKey("financial_period_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Beridian.Domain.Expenses.ExpenseDetail", b =>
                {
                    b.HasOne("Beridian.Domain.Expenses.Expense", null)
                        .WithMany("Details")
                        .HasForeignKey("expense_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Beridian.Domain.Common.Money", "PlannedAmount", b1 =>
                        {
                            b1.Property<Guid>("ExpenseDetailId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("planned_amount");

                            b1.Property<short>("Currency")
                                .HasColumnType("smallint")
                                .HasColumnName("planned_amount_currency");

                            b1.HasKey("ExpenseDetailId");

                            b1.ToTable("expense_details");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseDetailId");
                        });

                    b.Navigation("PlannedAmount");
                });

            modelBuilder.Entity("Beridian.Domain.FinancialPeriods.FinancialPeriod", b =>
                {
                    b.OwnsOne("Beridian.Domain.FinancialPeriods.Period", "Period", b1 =>
                        {
                            b1.Property<Guid>("FinancialPeriodId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("period_month");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("period_year");

                            b1.HasKey("FinancialPeriodId");

                            b1.HasIndex("Year", "Month")
                                .IsUnique()
                                .HasDatabaseName("ux_financial_periods_year_month");

                            b1.ToTable("financial_periods");

                            b1.WithOwner()
                                .HasForeignKey("FinancialPeriodId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("Beridian.Domain.Incomes.Income", b =>
                {
                    b.HasOne("Beridian.Domain.FinancialPeriods.FinancialPeriod", null)
                        .WithMany("Incomes")
                        .HasForeignKey("financial_period_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Beridian.Domain.Investments.Investment", b =>
                {
                    b.HasOne("Beridian.Domain.FinancialPeriods.FinancialPeriod", null)
                        .WithMany("Investments")
                        .HasForeignKey("financial_period_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Beridian.Domain.Expenses.Expense", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Beridian.Domain.FinancialPeriods.FinancialPeriod", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Incomes");

                    b.Navigation("Investments");
                });
#pragma warning restore 612, 618
        }
    }
}
